name: Build PDF and Push to Repository

on:
  push:
    branches:
      - main  # Runs when code is pushed to the main branch
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/extra # Use a container with Pandoc pre-installed

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: apt update && apt install -y pandoc

      - name: Run Make Command
        run: make

      - name: Commit and Push PDFs
        run: |
          git config --global --add safe.directory /__w/Q8_KUL/Q8_KUL  # Mark repo as safe
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@github.com"
          git add *.pdf
          # Get the last commit message
          LAST_COMMIT_MESSAGE=$(git log -1 --pretty=%B)

          # Construct the new commit message
          NEW_COMMIT_MESSAGE="[Compiled]: ${LAST_COMMIT_MESSAGE}"

          git commit -m "${NEW_COMMIT_MESSAGE}" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
